config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :surveys
  get 'homes/index'

  devise_for :users
  root 'surveys#index'
  get 'surveys/:id/view_responses', to: 'surveys#view_responses', as: :view_responses
  #APIs
  # api to get the list of existing survey
  get '/api/surveys', to: 'surveys#get_surveys_list'
  # api to add questions to the survey
  post '/api/surveys/:id/questions', to: 'surveys#add_questions'
  # api to get questions to the survey
  get '/api/surveys/:id/questions', to: 'surveys#get_questions'
  # api to delete questions to the survey
  delete 'api/surveys/:id/questions/:question_id', to: 'surveys#delete_questions'
  # api to take the survey
  post 'api/surveys/take_survey', to: 'surveys#take_survey'
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true

  validates_presence_of :title
  validates_uniqueness_of :title
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [
    :get_surveys_list, :add_questions, :delete_questions, :get_questions, :take_survey
  ]

  before_action :set_survey, only: [
    :show, :edit, :update, :destroy, :view_responses, :add_questions, :delete_questions, :get_questions
  ]

  before_action :authenticate_user!, except: [
    :get_surveys_list, :add_questions, :delete_questions, :get_questions, :take_survey
  ]

  before_action :authorize_admin, except: [
    :get_surveys_list, :add_questions, :delete_questions, :get_questions, :take_survey
  ]

  def index
    @surveys = Survey.all
  end

  def show
  end

  def new
    @survey = Survey.new
  end

  def edit
  end

  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def view_responses
    survey_questions = @survey.questions.includes(:answers)
    @survey_questions_content = survey_questions.map(&:content)
    @survey_answers_content = []
    survey_questions.each do |question|
      @survey_answers_content << question.answers.map(&:content)
    end
  end

  # APIs methods
  def get_surveys_list
    surveys = Survey.all
    render json: surveys
  end

  def add_questions
    survey_questions = @survey.questions.create!(content: params[:questions_attributes][:content])
    render json: survey_questions
  end

  def get_questions
    survey_questions = @survey.questions
    render json: survey_questions
  end

  def delete_questions
    question = @survey.questions.find(params[:question_id])
    question.destroy
    render json: { success: "Question deleted succesfully", status: 204 }
  end

  def take_survey
    question = Question.find(params[:questions_attributes][:id])
    question.answers.create!(content: params[:questions_attributes][:answers_attributes][:content])
    render json: { success: "Survey response added succesfully", status: 200 }
  end

  private
    def set_survey
      @survey = Survey.find(params[:id])
    end

    def survey_params
      params.require(:survey).permit(:title, questions_attributes: [ :id, :content, :_destroy, answers_attributes: [ :id, :content, :_destroy ] ])
    end

    def authorize_admin
      redirect_to main_app.homes_index_path unless current_user.is_admin == true
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Answer" %><br>
  <%= f.text_area :content, class: "form-control" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<%= form_for(survey) do |f| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Question", f, :questions %>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :content, "Question" %><br />
  <%= f.text_field :content, class: "form-control" %>
  <%#= f.check_box :_destroy %>
  <!-- <%#= f.label :_destroy, "Remove Question" %></br > -->
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove Question", '#', class: "remove_fields" %><br />
  <%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %>
</fieldset>

app/views/surveys/edit.html.erb
<br /><p class="lead">Editing Survey</p>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<br /><p class="lead">All Surveys</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.title %></td>
        <td><%= link_to 'View Responses', view_responses_path(survey), class: "btn btn-primary", style: "color: #ffffff" %></td>
        <td><%= link_to 'Show', survey, class: "btn btn-primary", style: "color: #ffffff" %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey), class: "btn btn-warning", style: "color: #ffffff" %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "color: #ffffff" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<br /><p class="lead">New Survey</p>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p></p>

<p>
  <strong>Title:</strong>
  <%= @survey.title %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Question(s)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey.questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/view_responses.html.erb
<br /><p class="lead">Survey Responses</p>

<table class="table table-striped">
  <thead>
    <tr>
      <% @survey_questions_content.each do |survey_question| %>
        <th><%= survey_question %></th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% i = 0 %>
  	<% @survey_answers_content.max_by{|x| x.length}.length.times do %>
  	  <tr>
  	    <% @survey_answers_content.each do |answer| %>
          <td><%= answer[i] %></td>
        <% end %>
        <% i+=1 %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', surveys_path %>